auth_enabled: false
limits_config:
  allow_structured_metadata: true
server:
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 168h
storage_config:
  filesystem:
    directory: /tmp/loki/chunks